rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/',
        views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path("category/<slug:category_name_slug>/add_page/",views.add_page, name="add_page"),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.name
    
class Page(models.Model):
    ## ForeignKey one to one (78)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    ## Implement 实现 （79）
    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, 
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page
        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # We can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        #fields = ('title', 'url', 'views')
    
    ##
    def clean(self):
        cleaned_data = super().clean()
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data
    
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page

def index(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage matches to {{ boldmessage }} in the template!
    # context_dict = {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!'}

    ## 只检索前5位 Retrieve the top 5 only -- or all if less than 5.
    category_list = Category.objects.order_by('-likes')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list

    pages = Page.objects.order_by('-views')[:5]
    context_dict['pages'] = pages

    top_categories = Category.objects.order_by("-likes")[:5]
    context_dict['top_categories'] = top_categories
    
    # Return a rendered response to send to the client.
    # We make use of the shortcut function to make our lives easier.
    # Note that the first parameter is the template we wish to use.
    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    
    context_dict = {'your_name': 'Xiaoshi Chen'}  
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
        # Can we find a category name slug with the given name?
        # If we can't, the .get() method raises a DoesNotExist exception.
        #   The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)
        # Retrieve all of the associated pages.
        # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)
        # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
        # We also add the category object from
        # the database to the context dictionary.
        # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
        # We get here if we didn't find the specified category.
        # Don't do anything -
        # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
    # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict)

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
About Rango
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <p>Here is the about page.</p>
    
    <div>
        hey there partner! <br />
        <strong>{{ your_name }}</strong> <br />
    </div>
    <li><a href="{% url 'rango:index' %}">Home</a></li>
    <div>
        <img src="/media/cat.jpg" alt = "Picture of Cat" /> 
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Add a Category
{% endblock %}

{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page to {{ category.name }}</h1>
    <div>
        <form id="add_page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page" />
        </form>
    </div>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
<head lang = "en">
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>

<body>
    <div>
        {% block body_block %}
            This is body_block's default content.
        {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
    
</body>

</html>

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
                <strong>
                <li> <a href = "{% url 'rango:show_category' c.slug %}">{{c.name}}</a></li>
                </strong>
            {% else %}
                <li> <a href = "{% url 'rango:show_category' c.slug %}">{{c.name}}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {%if category%}
        <h1>{{category.name}}</h1>
        {%if pages%}
        <ul>
            {%for page in pages%}
                <li><a href="{{page.url}}">{{page.title}}</a></li>
            {%endfor%}
        </ul>
        {%else%}
            <strong>No pages currently in category.</strong>
        {%endif%}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
        {% else %}
            Please <a href = "{% url 'rango:login' %}">log in</a> to add a page.
        {% endif %}
    {%else%}
        The specified category does not exist.
    {%endif%}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        hey there partner! <br />
        <strong>{{ boldmessage }}</strong> <br />
    </div>
    <!--  Most liked Categories-->
    <div>
        <h2>Most Liked Categories</h2>
        {% if top_categories %}
            <ul>
                {% for category in top_categories %}
                    <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <div>
                <strong>There are no categories present.</strong>
            </div>
        {% endif %}
    </div>

    <!-- Most Viewed Pages -->
    <div>
        <h2>Most Viewed Pages.</h2>
        {% if top_pages %}
            <ul>
                {% for page in top_pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <div>
                <strong>There are no pages present.</strong>
            </div>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'rango:about' %}">About</a><br />
        <a href="{% url 'rango:add_category' %}">Add a New Category</a><br>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" /> 
    </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Login
{% endblock %}


{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %} 
    <h1>Register for Rango</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
    Rango says: <strong>register here!</strong>
    <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
        
        {% csrf_token %}
        <!-- display both forms -->
        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Register" />
    </form>
    {% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <h1>Restricted Page</h1>
    <p>It's Restricted Page</p>
{% endblock %}